dreamspace/cart/urls.py
from django.urls import path
from . import views 


urlpatterns=[
path('',views.display_cart,name="cart"),
path('add-to-cart/<int:productId>/',views.add_to_cart,name="add-to-cart"),
path('update-cart/<int:cartitemId>/',views.update_cart,name="update-cart"),
path('delete-cartitem/<int:cartitemId>/',views.delete_cartitem,name="delete-cartitem"),
path('checkout/',views.checkout,name="checkout"),
path('payment/<str:orderId>/',views.payment,name="payment"),
path('success/<str:orderId>/',views.paymentSuccess,name="success"),
path('orders',views.orders,name="orders"),





]

dreamspace/dreamspace/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
# adding urls.py from products application
from products import urls
from django.conf.urls.static import static
from . import settings
from cart import urls
from consulatant import urls
from django.urls import path







urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('gallary/',views.gallary),
    path('calculator/',views.calculator),
    path('products/',include('products.urls')),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('cart/',include('cart.urls')),
    path('consulatant/',include('consulatant.urls')),
    path('download-pdf/', views.download_pdf, name='download-pdf'),
]





urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dreamspace/products/urls.py
from django.urls import path
from . import views
from .views import ProductDetailView

urlpatterns=[
    path('',views.ProductListView.as_view(),name="products"),
    path('products/<int:pk>/',views.ProductDetailView.as_view(),name="product-detail"),
      path('create-product/',views.ProductCreateView.as_view(),name="create-product"),
    path('update-product/<int:pk>/',views.ProductUpdateView.as_view(),name="product-update"),
    path('delete-product/<int:pk>/',views.ProductDeleteView.as_view(),name="product-delete"),
    path('search',views.search,name="search"),
    path('<slug:slug>/',views.CategoryDetailView.as_view(),name="category-detail"),
   

     
]

dreamspace/products/models.py
from django.db import models
from autoslug import AutoSlugField

class ProductCustomManager(models.Manager):
     def get_queryset(self):
          return super().get_queryset()  #to get all object
     
     

class Category(models.Model):
     category_name=models.CharField(max_length=100,null=False)
     category_slug=AutoSlugField(populate_from="category_name",unique=True)

     def __str__(self):
         return self.category_name





# Create your models here.
class Product(models.Model):
     product_name=models.CharField(max_length=100,null=False)
     product_description=models.CharField(max_length=200,null=False)
     product_price=models.PositiveIntegerField(default=0)
     product_image=models.ImageField(upload_to="products/")  
     product_brand=models.CharField(max_length=100)


 # one to many relationship then we use foreign key
     category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)


     customManager=ProductCustomManager()

     def __str__(self):
          return self.product_name
     

  

dreamspace/products/views.py
from django.shortcuts import render
from .models import Product,Category
from django.views.generic import DetailView,ListView,CreateView,UpdateView,DeleteView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required


# Create your views here.

def products(request):
    return render(request,"products.html")





def product_list(request):
    products = Product.objects.all()  # Get all products from the database
    return render(request, 'products.html', {'products': products})



class ProductDetailView(DetailView):
    model=Product
    template_name="products/productdetail.html"


class ProductListView(ListView):
    model=Product
    



@method_decorator(staff_member_required,name="dispatch")
class ProductCreateView(CreateView):
    model=Product
    fields="__all__"
    success_url="/products"

@method_decorator(staff_member_required,name="dispatch")
class ProductUpdateView(UpdateView):
    model=Product
    fields="__all__"
    success_url="/products"


@method_decorator(staff_member_required,name="dispatch")
class ProductDeleteView(DeleteView):
    model=Product
    success_url="/products"



def search(request):
    keyword=request.GET.get("keyword") 
    products=Product.customManager.all().filter(product_name__icontains=keyword)             
    return render(request,"products/product_list.html",{"object_list":products})

class CategoryDetailView(DetailView):
    model=Category
    template_name="category/category_detail.html"
    slug_field="category_slug"
    context_object_name="category_obj"      


    def get_context_data(self, **kwargs):

        context=super().get_context_data(**kwargs)
        context["categories"]=Category.objects.all()
        return context
    

dreamspace/products/templates/category/category_detail.html
 
{%load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="{% static '/css/products.css' %}">
    
    <script src="https://unpkg.com/phosphor-icons"></script>
    

    


</head>
<body>
  

  <!-- nav start -->
 
  <!-- Header section start -->
 


  <nav class="navbar">
    <div class="logo">DreamSpace</div>
    <ul class="nav-links">
      <li><a href="#">Home</a></li>
      <li><a href="#footer">About Us</a></li>
      <li><a href="{% url 'products' %}">Products</a></li>
    

    <div class="search-login">
      <li> <form class="d-flex w-10" action="{% url 'search' %}">
        <input class="form-control me-2 w-15 " type="search" placeholder="Search" aria-label="Search" name="keyword">
         <button class="btn btn-outline-success " type="submit">Search</button>
        </form></li>


        {% if request.user.first_name %}
  
        <a class="btn btn-outline-light"  href="{% url 'login'%}" role="button">{{request.user.first_name}}</a>
        <a class="btn btn-outline-light" href="{% url 'logout'%}" role="button">Logout</a>
        
        
        {% else %}
  
        <a class="btn btn-outline-light" href="{% url 'login'%}" role="button">Login</a>
        <a class="btn btn-outline-light" href="{% url 'register' %}" role="button" id="button">Register</a>
        
      
        {% endif %}

    </div>
    <a href="{% url 'cart' %}">  <div class="notification">
      <i class="fas fa-shopping-bag icon"></i>
      {% if count %}
      <div class="badge">{{count}}</div>
  </div></a>
  {% endif %} 

    </ul>

  </nav>
  


 <!-- shop heading start -->

<div class="text">
  <div id="shop">
    <p>Shop</p>
  </div>
</div>

<!-- shop heading end -->

<!-- Offer section start -->

<div class="discount">
  <div class="disc">
    <p>
      BIG SALE OFF ALL ITEMS UP TO 50% OFF
      Coming soon on December.<a href="">View more</a></p>
      

  </div>
</div>


 <!-- offer section end -->



<!-- <h1>Shop</h1> -->
<section class="product" id="product">

  <h1 class="heading"><span>Product</span> </h1>

  <div class="box-container" >

    

{% for product in category_obj.product_set.all  %}

 {% include "card.html" with p=product%}

{% endfor %}



</div>
</section>


<!-- footer start -->

  
<div id="footer">
  <div class="foot-panel1"><a href="#home">Back to top</a></div>
  <div class="foot-panel2">
      <ul>
          <p>Get to Know Us</p>

          <a>careers</a>
          <br>
          <a>About DreamSpace</a>
          <br>
          <a>Portpholio</a>
          <br>
          <a>DreamSpace Services</a>

      </ul>

      <ul>
          <p>Connect with Us</p>
          <a>Facebook</a>
          <br>
          <a>Twitter</a>
          <br>
          <a>Instagram</a>
         

      </ul>
      <ul>
          <p>Make Money with Us</p>
          <a>Built with DreamSpace</a>
          <br>
          <a>Fullfillment by DreamSpace </a>
          <br>
          <a>Protect and Build Your Home </a>
          <br>
          <a> DreamSpace Pay on Merchants</a>
      </ul>
</div>
</div>
</div>

<!-- footer end -->









</html>